/* Mi Turronera V15 - capa multiusuario Supabase */
const TUR_SUPABASE_URL='https://wzpvfgfiietibsgsfmge.supabase.co';
const TUR_SUPABASE_KEY='sb_publishable_XZWydO6V169D1OOdwiyYRA_lhg6PkIv';
const TUR_AUTHORIZED=['jpiscoyach82@gmail.com','cemariafe1986@gmail.com'];
const turCloud=window.supabase.createClient(TUR_SUPABASE_URL,TUR_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let turBusinessId=null,turUser=null,turRole=null,turChannel=null,turApplyingRemote=false,turSyncTimer=null;
const TUR_PENDING_KEY='tur_v15_pending';
function turPending(){try{return JSON.parse(localStorage.getItem(TUR_PENDING_KEY)||'{}')}catch{return{}}}
function turSavePending(x){localStorage.setItem(TUR_PENDING_KEY,JSON.stringify(x))}
function turEnqueue(rec){const q=turPending();q[rec.code]=rec;turSavePending(q);turSetState('bad',navigator.onLine?'Pendiente de sincronizar':'Sin conexión · cambios guardados')}
async function turFlushPending(){if(!navigator.onLine||!turBusinessId||!turUser)return;const q=turPending();for(const code of Object.keys(q)){try{await turPushRecord(q[code],true);delete q[code];turSavePending(q)}catch(e){break}}}
const turCacheKey='tur_v15_cache';
function turSetState(state,text){const d=document.getElementById('syncDot'),t=document.getElementById('syncText');if(d)d.className='syncdot '+state;if(t)t.textContent=text;}
function turShowGate(show){const g=document.getElementById('authGate');if(g)g.style.display=show?'flex':'none';document.body.classList.toggle('authRequired',show)}
function turLocalHistory(){try{const x=JSON.parse(localStorage.getItem('tur_v1414')||localStorage.getItem(turCacheKey)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function turWriteLocalHistory(x){localStorage.setItem('tur_v1414',JSON.stringify(x));localStorage.setItem(turCacheKey,JSON.stringify(x));}
async function turClaim(){const {data,error}=await turCloud.rpc('claim_my_access');if(error)throw error;turBusinessId=data?.[0]?.business_id;turRole=data?.[0]?.role||null;window.TUR_ROLE=turRole;document.body.dataset.role=turRole||'';if(typeof window.applyRoleUI==='function')window.applyRoleUI(turRole);if(!turBusinessId)throw new Error('No se pudo identificar el negocio.');}
async function turPull(){if(!turBusinessId)return;turSetState('working','Actualizando…');const [{data:rows,error},{data:settings,error:se}]=await Promise.all([turCloud.from('turroneras').select('id,code,data,revision,updated_at').eq('business_id',turBusinessId).is('deleted_at',null).order('updated_at',{ascending:false}),turCloud.from('business_settings').select('prices,revision').eq('business_id',turBusinessId).maybeSingle()]);if(error)throw error;if(se)throw se;turApplyingRemote=true;try{turWriteLocalHistory((rows||[]).map(r=>({...r.data,_cloudId:r.id,_revision:r.revision})));if(settings?.prices){localStorage.setItem('tur_prices_v10',JSON.stringify(settings.prices));if(typeof window.applyCloudPrices==='function')window.applyCloudPrices(settings.prices)}}finally{turApplyingRemote=false}if(typeof renderDashboard==='function')renderDashboard();if(typeof renderHistory==='function')renderHistory();turSetState('ok','Sincronizado');}
async function turPushRecord(rec,fromQueue=false){if(!turBusinessId||!turUser||turApplyingRemote)return;turSetState('working','Guardando…');const payload={...rec};delete payload._cloudId;delete payload._revision;const base={business_id:turBusinessId,code:rec.code,data:payload,updated_by:turUser.id,client_updated_at:new Date().toISOString()};let q;if(rec._cloudId){q=turCloud.from('turroneras').update(base).eq('id',rec._cloudId).eq('revision',rec._revision||1).select('id');}else{q=turCloud.from('turroneras').upsert({...base,created_by:turUser.id},{onConflict:'business_id,code'}).select('id');}const {data:saved,error}=await q;if(error){if(!fromQueue)turEnqueue(rec);turSetState('bad',navigator.onLine?'Error · cambio guardado':'Sin conexión · cambio guardado');throw error}if(rec._cloudId&&(!saved||saved.length===0)){await turPull();turSetState('bad','Conflicto: datos actualizados en otro celular');window.dispatchEvent(new CustomEvent('tur-conflict',{detail:{code:rec.code}}));throw new Error('Conflicto de edición: se cargó la versión más reciente. Repite tu cambio.')}await turPull();}
async function turPushAllLocal(list=turLocalHistory(),prices=null){for(const rec of list){await turPushRecord(rec)}if(prices){localStorage.setItem('tur_prices_v10',JSON.stringify(prices));}await turPushPrices();}
async function turPushPrices(){if(!turBusinessId||!turUser)return;let prices;try{prices=JSON.parse(localStorage.getItem('tur_prices_v10')||'null')}catch{};if(!prices)return;const {error}=await turCloud.from('business_settings').update({prices,updated_by:turUser.id}).eq('business_id',turBusinessId);if(error)throw error;}
async function turTrashOne(id){if(turRole!=='admin')throw new Error('Solo el administrador puede borrar.');if(!id)return;const {error}=await turCloud.rpc('admin_trash_turronera',{p_id:id});if(error)throw error;await turPull()}
async function turTrashAll(){if(turRole!=='admin')throw new Error('Solo el administrador puede borrar datos.');if(!turBusinessId||!turUser)return;const {error}=await turCloud.rpc('admin_trash_all',{p_business:turBusinessId});if(error)throw error;await turPull();}
async function turTrashList(){if(turRole!=='admin'||!turBusinessId)return[];const {data,error}=await turCloud.from('turroneras').select('id,code,deleted_at,data').eq('business_id',turBusinessId).not('deleted_at','is',null).order('deleted_at',{ascending:false});if(error)throw error;return data||[]}
async function turRestore(id){if(turRole!=='admin')throw new Error('Solo el administrador puede restaurar.');const {error}=await turCloud.rpc('admin_restore_turronera',{p_id:id});if(error)throw error;await turPull()}
async function turAudit(limit=40){if(!turBusinessId)return[];const {data,error}=await turCloud.rpc('get_my_business_activity',{p_limit:limit});if(error)throw error;return data||[];}
function turQueueRecord(rec){if(!turUser||!turBusinessId)return;if(!navigator.onLine){turEnqueue(rec);return}clearTimeout(turSyncTimer);turSyncTimer=setTimeout(()=>turPushRecord(rec).catch(console.error),150)}
window.addEventListener('offline',()=>turSetState('bad','Sin conexión · modo seguro'));
window.addEventListener('online',()=>{turSetState('working','Reconectando…');turFlushPending().then(()=>turPull()).catch(()=>turSetState('bad','Error al sincronizar'))});
function turSubscribe(){if(turChannel)turCloud.removeChannel(turChannel);turChannel=turCloud.channel('mi-turronera-'+turBusinessId).on('postgres_changes',{event:'*',schema:'public',table:'turroneras',filter:`business_id=eq.${turBusinessId}`},()=>turPull().catch(console.error)).on('postgres_changes',{event:'*',schema:'public',table:'business_settings',filter:`business_id=eq.${turBusinessId}`},()=>turPull().catch(console.error)).subscribe(s=>{if(s==='SUBSCRIBED'){turSetState('ok','Sincronizado');turFlushPending().catch(console.error)}});}
async function turStart(session){turUser=session?.user||null;if(!turUser){turShowGate(true);turSetState('bad','Sin sesión');return}if(!TUR_AUTHORIZED.includes((turUser.email||'').toLowerCase())){await turCloud.auth.signOut();turShowGate(true);document.getElementById('authMsg').textContent='Este correo no está autorizado.';return}turShowGate(false);document.getElementById('signOut').style.display='inline-block';await turClaim();const {count}=await turCloud.from('turroneras').select('*',{count:'exact',head:true}).eq('business_id',turBusinessId);await turPull();turSubscribe();}
window.TurroneraCloud={queueRecord:turQueueRecord,pushPrices:()=>turPushPrices(),pull:()=>turPull(),pushOfficialBackup:(history,prices)=>turPushAllLocal(history,prices),isReady:()=>!!turBusinessId,getRole:()=>turRole,isAdmin:()=>turRole==='admin',trashOne:(id)=>turTrashOne(id),trashAll:()=>turTrashAll(),trashList:()=>turTrashList(),restore:(id)=>turRestore(id),audit:(n)=>turAudit(n)};
window.addEventListener('online',()=>turPull().catch(()=>turSetState('bad','Pendiente de sincronizar')));window.addEventListener('offline',()=>turSetState('bad','Sin conexión · datos locales'));
document.addEventListener('DOMContentLoaded',async()=>{const send=document.getElementById('authSend');send.onclick=async()=>{const email=(document.getElementById('authEmail').value||'').trim().toLowerCase(),msg=document.getElementById('authMsg');if(!TUR_AUTHORIZED.includes(email)){msg.textContent='Ese correo no está autorizado.';return}send.disabled=true;msg.textContent='Enviando enlace seguro…';const {error}=await turCloud.auth.signInWithOtp({email,options:{shouldCreateUser:true,emailRedirectTo:location.href.split('#')[0]}});send.disabled=false;msg.textContent=error?('No se pudo enviar: '+error.message):'Revisa tu correo y abre el enlace de acceso.'};document.getElementById('signOut').onclick=async()=>{if(turChannel){await turCloud.removeChannel(turChannel);turChannel=null}turBusinessId=null;turUser=null;turRole=null;await turCloud.auth.signOut();};const {data:{session}}=await turCloud.auth.getSession();await turStart(session).catch(e=>{console.error(e);turSetState('bad','Error de sincronización')});turCloud.auth.onAuthStateChange((_e,s)=>setTimeout(()=>turStart(s).catch(console.error),0));});
